import bcrypt from 'bcryptjs';

export const data = {
  products: [
    {
      _id: '1',
      name: 'Nike Slim Shirt',
      slug: 'nike-slim-shirt',
      category: 'Shirts',
      image: '/images/nike-slim-shirt.webp',
      price: 120,
      qtyInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      qtyReviews: 10,
      description: 'high quality shirt',
    },
    {
      _id: '2',
      name: 'Nike Slim Pants',
      slug: 'nike-slim-pants',
      category: 'Pants',
      image: '/images/nike-slim-pants.webp',
      price: 130,
      qtyInStock: 0,
      brand: 'Nike',
      rating: 4.7,
      qtyReviews: 18,
      description: 'high quality pants',
    },
    {
      _id: '3',
      name: 'Adidas Fit Shirt',
      slug: 'adidas-fit-shirt',
      category: 'Shirts',
      image: '/images/adidas-fit-shirt.webp',
      price: 100,
      qtyInStock: 8,
      brand: 'Adidas',
      rating: 4.1,
      qtyReviews: 17,
      description: 'high quality fitness shirt',
    },
    {
      _id: '4',
      name: 'Adidas Fit Joggers',
      slug: 'adidas-fit-joggers',
      category: 'Pants',
      image: '/images/adidas-fit-joggers.webp',
      price: 110,
      qtyInStock: 15,
      brand: 'Adidas',
      rating: 3.8,
      qtyReviews: 21,
      description: 'high quality fitness joggers',
    },
  ],
  users: [
    {
      id: '',
      name: 'Michael leCour',
      email: 'test-admin@test.com',
      password: bcrypt.hashSync('admin-user1'),
      is_admin: true,
    },
    {
      id: '',
      name: 'Mary Jane',
      email: 'test2@test.com',
      password: bcrypt.hashSync('123456'),
      is_admin: false,
    },
    {
      id: '',
      name: 'John Doe',
      email: 'test3@test.com',
      password: bcrypt.hashSync('123456'),
      is_admin: false,
    },
  ],
};
