export const data = {
  products: [
    {
      name: 'Nike Slim Shirt',
      slug: 'nike-slim-shirt',
      category: 'Shirts',
      image: '/images/image-name.jpg',
      price: 120,
      qtyInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      qtyReviews: 10,
      description: 'high quality shirt',
    },
    {
      name: 'Nike Slim Pants',
      slug: 'nike-slim-pants',
      category: 'Pants',
      image: '/images/image-name.jpg',
      price: 130,
      qtyInStock: 12,
      brand: 'Nike',
      rating: 4.7,
      qtyReviews: 18,
      description: 'high quality pants',
    },
    {
      name: 'Adidas Fit Shirt',
      slug: 'adidas-fit-shirt',
      category: 'Shirts',
      image: '/images/image-name.jpg',
      price: 100,
      qtyInStock: 8,
      brand: 'Adidas',
      rating: 4.3,
      qtyReviews: 17,
      description: 'high quality fitness shirt',
    },
    {
      name: 'Adidas Fit Joggers',
      slug: 'adidas-fit-joggers',
      category: 'Pants',
      image: '/images/image-name.jpg',
      price: 130,
      qtyInStock: 15,
      brand: 'Adidas',
      rating: 4.8,
      qtyReviews: 21,
      description: 'high quality fitness joggers',
    },
  ],
};
